package com.csye.Fall.cloud.datamodel;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName="Courses")
public class Course {
	private String id;
	private String courseId;
	private String professorId;
	private String studentTaId;
	private String department;
	private String boradId;
	private List<String> studentIds;

	
	public Course() {
		
	}


	@DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }
    public void setId(String id) { this.id = id; } 
    
   
    @DynamoDBIndexHashKey(globalSecondaryIndexName="courseId-index",attributeName="courseId")
	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}


	@DynamoDBAttribute(attributeName="professorId")
	public String getProfessorId() {
		return professorId;
	}

	public void setProfessorId(String professorId) {
		this.professorId = professorId;
	}


	@DynamoDBAttribute(attributeName="studentTaId")
	public String getStudentTaId() {
		return studentTaId;
	}

	public void setStudentTaId(String studentTaId) {
		this.studentTaId = studentTaId;
	}

	@DynamoDBAttribute(attributeName="department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAttribute(attributeName="boardId")
	public String getBoradId() {
		return boradId;
	}

	public void setBoradId(String boradId) {
		this.boradId = boradId;
	}

	@DynamoDBAttribute(attributeName="studentIds")
	public List<String> getStudentIds() {
		return studentIds;
	}

	public void setStudentIds(List<String> studentIds) {
		this.studentIds = studentIds;
	}
	
   
	@DynamoDBIgnore
	@Override
	public String toString() { 
		return "courseId=" + getCourseId() + ", professorId=" + getProfessorId();
	}

	
}
